// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyectoef;

#nullable disable

namespace aplicacion_web.Migrations
{
    [DbContext(typeof(TareasContext))]
    [Migration("20240315194652_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("proyectoef.Models.Categoria", b =>
                {
                    b.Property<Guid>("categoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("peso")
                        .HasColumnType("int");

                    b.HasKey("categoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            categoriaId = new Guid("2b399f2a-3c7e-4ca5-a53d-dd893967099f"),
                            nombre = "Actividades pendientes",
                            peso = 20
                        },
                        new
                        {
                            categoriaId = new Guid("2b399f2a-3c7e-4ca5-a53d-dd893967001c"),
                            nombre = "Actividades personales",
                            peso = 50
                        });
                });

            modelBuilder.Entity("proyectoef.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("2b399f2a-3c7e-4ca5-a53d-dd893967033c"),
                            CategoriaId = new Guid("2b399f2a-3c7e-4ca5-a53d-dd893967099f"),
                            FechaCreacion = new DateTime(2024, 3, 15, 14, 46, 52, 337, DateTimeKind.Local).AddTicks(7101),
                            MyProperty = 0,
                            PrioridadTarea = 1,
                            titulo = "pago de servicios publicos"
                        },
                        new
                        {
                            TareaId = new Guid("2b399f2a-3c7e-4ca5-a53d-d33eeddee34d"),
                            CategoriaId = new Guid("2b399f2a-3c7e-4ca5-a53d-dd893967001c"),
                            FechaCreacion = new DateTime(2024, 3, 15, 14, 46, 52, 337, DateTimeKind.Local).AddTicks(7116),
                            MyProperty = 0,
                            PrioridadTarea = 2,
                            titulo = "pago de hipoteca"
                        });
                });

            modelBuilder.Entity("proyectoef.Models.Tarea", b =>
                {
                    b.HasOne("proyectoef.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyectoef.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
