--  UN TRIGGER ES UN DESENCADENADOR DE EVENTOS QUE SE EJECUTA APARTIR DE LOS SIGUIENTES METODOS, FUNCIONA PARA REGISTRAR CAMBIOS DEUNA TABLA 
--	(1) INSERT 
--	(2) UPDATE 
--	(3) DELETE


CREATE TRIGGER PacientesCreados on Paciente
AFTER INSERT 
AS

IF(SELECT idPais FROM inserted) = 'MEX'
	INSERT INTO PacienteLog (idPaciente,idPais,fechaAlta)
		SELECT i.idPaciente,i.idPais,GETDATE() FROM inserted i 