
--INNER JOIN OBTIENE LOS CAMPOS DE 2 TABLAS RELACIONADAS, LOS UNE EN UNA SOLA DE MANERA QUE FILTRA Y MUESTRA DOLO LOS VALORES DE LOS CAMPOS QUE COINCIDEN ENTRE AMBAS
SELECT * FROM Paciente AS P 
INNER JOIN TurnoPaciente AS T
ON P.idPaciente = T.idPaciente